name: MinaJS Continuous Integration
on:
  push:
    branches: [main]
jobs:
  test_and_release:
    name: Test and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun i --no-save
      - run: bun run build
      - run: bun run test
      - run: bunx pkg-pr-new publish './packages/klesia-sdk' './packages/accounts' './packages/connect' './packages/providers'
