name: Promote Docker image to latest
on:
  workflow_dispatch:
    inputs:
      commitShort:
        description: "Short commit hash"
        required: true
jobs:
  promote_image:
    name: Tag latest and push to GHCR
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag image
        run: docker buildx imagetools create ghcr.io/palladians/klesia:${{ github.event.inputs.commitShort }} --tag ghcr.io/palladians/klesia:latest
