name: Dockerize Klesia
on:
  workflow_dispatch:
jobs:
  dockerize_and_push:
    name: Dockerize Klesia and push to GHCR
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set Docker tag
        run: echo "IMAGE_STAMP=ghcr.io/palladians/klesia:$(git rev-parse --short HEAD)" > "$GITHUB_ENV"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        uses: iloveitaly/github-action-nixpacks@main
        with:
          context: ". --config apps/klesia/nixpacks.toml"
          platforms: "linux/amd64,linux/arm64"
          push: true
          tags: ghcr.io/palladians/klesia:${{ env.IMAGE_STAMP }}
